#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#FUNCTION: Export COM calculation results and plots
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @title Export COM calculation results as .CSV and graphics
#'
#' @description Exports the results and (if any) plots generated by \code{\link{calcom}}.
#'
#' @param comres The output of function \code{\link{calcom}}.
#' @param expath The \strong{existing} export folder path.
#' @param plotpars A \strong{named} \code{numeric} vector of plotting parameters, including:
#' width (\code{["w"]}, in inches), height (\code{["h"]}), point size (\code{["psize"]}), and dots per inch or DPI (\code{["dpi"]}).
#' Initially set to \code{"default"}, i.e. \code{c(w = 10, h = 12, psize = 12, dpi = 300)}.
#' @param plot_format Format of plots to export. One of \code{"png"} (default) or \code{"pdf"}.
#' @param silent Should console output be silenced? Defaults to \code{FALSE}).
#'
#' @return A .CSV file and any accompanying graphics (where present in \code{comres}) are expoted to \code{expath}.
#' @export
#'
#' @seealso \code{\link{calcom}}
#'
#' @importFrom ggplot2 ggsave
#' @importFrom data.table fwrite
#'
com_export <- function(comres, expath = getwd(), plotpars = "default", plot_format = "png", silent = FALSE) {

  #Set the delimiter
  fwsep <- "\t"

  #Preliminary checks
  if(inherits(comres[["call"]],"call")) funcall <- format(comres[["call"]])
  if(!all(c("input", "output", "simple_output", "extra", "call") %in% names(comres)))
    stop("The input data 'comres' must be output from function 'calcom'!")
  if(!dir.exists(expath)) stop("The selected export directory doesn't exist!")
  if(!plot_format %in% c("png","pdf")) stop("The output format for plots must be one of: 'png', 'pdf'!")

  #Set up plot parameters
  defpars <- c(w = 10, h = 12, psize = 12, dpi = 300)
  plotpars <- supp_pars(pars = plotpars, defpars = defpars, parlb = "plotpars")

  #Prepare/create export directory
  expath <- paste0(expath, "/COM_", format(Sys.time(), "%Y-%m-%d %Hhr %Mmin %Ssec"))
  if(!silent) cat("\nExport path: ", expath, "...")

  #Create main output dir
  invisible(dir.create(expath))

  #Export plots
  if(any(names(comres) %in% "plots")) {
    #Create plot output dir
    expath_plots <- paste0(expath, "/Plots")
    invisible(dir.create(expath_plots))

    if(!silent) cat("\nExporting plots...")
    for(i in names(comres[["plots"]])) {
      ggsave(paste0(expath_plots, "/", i,".",plot_format), comres[["plots"]][[i]],
             height = plotpars["h"], width = plotpars["w"], units = "in", pointsize = plotpars["psize"],
             dpi = plotpars["dpi"], device = plot_format)
    }
  }

  #Export data to a single .CSV
  if(!silent) cat("\nExporting data...")
  fpath <- paste0(expath, "/Cost_of_Manufacturing_Results.tab")

  cat("COST OF MANUFACTURING ANALYSIS RESULTS FOR RESPONSE: ", toupper(colnames(comres[["simple_output"]])[2]), file = fpath, sep = "", append = TRUE)
  cat("\nINPUT DATA PROVIDED BY USER\n", file = fpath, sep = "", append = TRUE)
  fwrite(comres[["input"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)

  cat("\n\nDETAILED OUTPUT DATA\n", file = fpath, sep = "", append = TRUE)
  fwrite(comres[["output"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)

  cat("\n\nABBREVIATED OUTPUT DATA", file = fpath, sep = "", append = TRUE)
  cat(comres[["rm_state"]], "\n", file = fpath, sep = "", append = TRUE)
  fwrite(comres[["simple_output"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)

  cat("\n\nADDITIONAL RESULTS\n", file = fpath, sep = "", append = TRUE)
  cat(names(comres[["extra"]]), file = fpath, sep = fwsep, append = TRUE)
  cat("\n", file = fpath, append = TRUE)
  cat(comres[["extra"]], file = fpath, sep = fwsep, append = TRUE)
  cat("\n", file = fpath, append = TRUE)

  if(is.character(funcall)) {
    cat("\n\nFUNCTION CALL\n", file = fpath, append = TRUE)
    cat(funcall, file = fpath, sep = "", append = TRUE)
  }
  if(!silent) cat("\nDONE!")
}
