#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#FUNCTION: Export COM calculation results and plots
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @title Export COM calculation results as .CSV and graphics
#'
#' @description Exports the results and (if any) plots generated by \code{\link{calcom}}.
#'
#' @param comres The output of function \code{\link{calcom}}.
#' @param expath The \strong{existing} export folder path.
#' @param plotpars A \strong{named} \code{numeric} vector of plotting parameters, including:
#' width (\code{["w"]}, in inches), height (\code{["h"]}), point size (\code{["psize"]}), and dots per inch or DPI (\code{["dpi"]}).
#' Initially set to \code{"default"}, i.e. \code{c(w = 10, h = 12, psize = 12, dpi = 300)}.
#' @param plot_format Format of plots to export. One of \code{"png"} (default) or \code{"pdf"}.
#' @param silent Should console output be silenced? Defaults to \code{FALSE}).
#'
#' @return A .CSV file and any accompanying graphics (where present in \code{comres}) are expoted to \code{expath}.
#' @export
#'
#' @seealso \code{\link{calcom}}
#'
#' @importFrom ggplot2 ggsave
#' @importFrom data.table fwrite
#'
com_export <- function(comres, expath = getwd(), plotpars = "default", plot_format = "png", silent = FALSE) {

  #Set the delimiter
  fwsep <- ","

  #Preliminary checks
  if(inherits(comres[["call"]],"call")) funcall <- format(comres[["call"]])
  if(!all(c("input", "output", "simple_output", "extra", "call") %in% names(comres)))
    stop("The input data 'comres' must be output from function 'calcom'!")
  if(!dir.exists(expath)) stop("The selected export directory doesn't exist!")
  if(!plot_format %in% c("png","pdf")) stop("The output format for plots must be one of: 'png', 'pdf'!")

  #Set up plot parameters
  defpars <- c(w = 10, h = 12, psize = 12, dpi = 300)
  plotpars <- supp_pars(pars = plotpars, defpars = defpars, parlb = "plotpars")

  #Prepare/create export directory
  expath <- paste0(expath, "/COM_", format(Sys.time(), "%Y-%m-%d %Hhr %Mmin %Ssec"))
  if(!silent) cat("\nExport path: ", expath, "...")

  #Create main output dir
  invisible(dir.create(expath))

  #Export plots
  if(any(names(comres) %in% "plots")) {
    #Create plot output dir
    expath_plots <- paste0(expath, "/Plots")
    invisible(dir.create(expath_plots))

    if(!silent) cat("\nExporting plots...")
    for(i in names(comres[["plots"]])) {
      ggsave(paste0(expath_plots, "/", i,".",plot_format), comres[["plots"]][[i]],
             height = plotpars["h"], width = plotpars["w"], units = "in", pointsize = plotpars["psize"],
             dpi = plotpars["dpi"], device = plot_format)
    }
  }

  #Export data using structured tables if available
  if(!silent) cat("\nExporting data...")
  fpath <- paste0(expath, "/Cost_of_Manufacturing_Results.csv")

  cat("COST OF MANUFACTURING ANALYSIS RESULTS\n", file = fpath, sep = "", append = TRUE)
  cat("Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n", file = fpath, sep = "", append = TRUE)
  cat(paste0(rep("=", 60), collapse = ""), "\n\n", file = fpath, sep = "", append = TRUE)

  #Use structured tables if available (new format)
  if(!is.null(comres[["tables"]])) {
    tables <- comres[["tables"]]
    
    #1. Production Overview
    cat("PRODUCTION OVERVIEW\n", file = fpath, sep = "", append = TRUE)
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    fwrite(tables[["production"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
    cat("\n", file = fpath, append = TRUE)
    
    #2. Cost of Raw Materials (CRM)
    cat("\nCOST OF RAW MATERIALS (CRM)\n", file = fpath, sep = "", append = TRUE)
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    fwrite(tables[["crm"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
    cat("\n", file = fpath, append = TRUE)
    
    #3. Cost of Utilities (CUT)
    cat("\nCOST OF UTILITIES (CUT)\n", file = fpath, sep = "", append = TRUE)
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    fwrite(tables[["cut"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
    cat("\n", file = fpath, append = TRUE)
    
    #4. Financial Results (Combined Summary)
    cat("\nFINANCIAL RESULTS (COMBINED SUMMARY)\n", file = fpath, sep = "", append = TRUE)
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    fwrite(tables[["financial"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
    cat("\n", file = fpath, append = TRUE)
    
    #5. Per-Response Financial Tables (if multiple responses)
    if(!is.null(tables[["per_response"]])) {
      cat("\nPER-RESPONSE FINANCIAL BREAKDOWN\n", file = fpath, sep = "", append = TRUE)
      cat(paste0(rep("=", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
      
      for(resp_name in names(tables[["per_response"]])) {
        cat("\n", resp_name, "\n", file = fpath, sep = "", append = TRUE)
        cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
        fwrite(tables[["per_response"]][[resp_name]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
        cat("\n", file = fpath, append = TRUE)
      }
    }
    
    #6. Performance Overview (time-series data)
    if(!is.null(tables[["performance"]])) {
      cat("\nPERFORMANCE OVERVIEW (TIME-SERIES DATA)\n", file = fpath, sep = "", append = TRUE)
      cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
      if(!is.null(comres[["rm_state"]])) {
        cat(comres[["rm_state"]], "\n", file = fpath, sep = "", append = TRUE)
      }
      fwrite(tables[["performance"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
      cat("\n", file = fpath, append = TRUE)
    }
    
  } else {
    #Fallback to old format for backward compatibility
    cat("INPUT DATA PROVIDED BY USER\n", file = fpath, sep = "", append = TRUE)
    fwrite(comres[["input"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)

    cat("\n\nDETAILED OUTPUT DATA\n", file = fpath, sep = "", append = TRUE)
    fwrite(comres[["output"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)

    cat("\n\nABBREVIATED OUTPUT DATA", file = fpath, sep = "", append = TRUE)
    cat(comres[["rm_state"]], "\n", file = fpath, sep = "", append = TRUE)
    fwrite(comres[["simple_output"]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
  }

  #Input parameters section (structured to match UI layout)
  cat("\n\nINPUT PARAMETERS\n", file = fpath, sep = "", append = TRUE)
  cat(paste0(rep("=", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
  
  inpars <- comres[["input"]]
  cn <- colnames(inpars)
  
  #Find columns by checking lowercase version or common translations
  lcn <- tolower(cn)
  
  #Try to find type column - check for common patterns
  type_idx <- which(lcn %in% c("type", "тип", "tür"))[1]
  if(is.na(type_idx)) type_idx <- 4  #Fallback to 4th column
  
  value_idx <- which(lcn %in% c("value", "значение", "değer"))[1]
  if(is.na(value_idx)) value_idx <- 2
  
  units_idx <- which(lcn %in% c("units", "единицы", "birim"))[1]
  if(is.na(units_idx)) units_idx <- 3
  
  desc_idx <- which(lcn %in% c("description", "описание", "açıklama"))[1]
  if(is.na(desc_idx)) desc_idx <- 5
  
  type_col <- cn[type_idx]
  value_col <- cn[value_idx]
  units_col <- cn[units_idx]
  desc_col <- cn[desc_idx]
  
  #Helper function to write a category (matching Shiny UI: Description, Value, Unit)
  write_category <- function(title, type_values) {
    params <- inpars[inpars[[type_col]] %in% type_values, ]
    if(nrow(params) > 0) {
      cat("\n", title, "\n", file = fpath, sep = "", append = TRUE)
      cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
      #Output only Description, Value, Units (matching Shiny UI)
      out_params <- params[, c(desc_col, value_col, units_col)]
      colnames(out_params) <- c("Description", "Value", "Unit")
      fwrite(out_params, file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
      cat("\n", file = fpath, append = TRUE)
    }
  }
  
  #Check if type column has expected values
  type_vals <- unique(inpars[[type_col]])
  has_categories <- any(c("general", "gen", "crm", "cut", "col", "fci") %in% type_vals)
  
  if(has_categories) {
    write_category("General Parameters", c("general", "gen"))
    write_category("Raw Material Parameters", c("crm", "crm_aux"))
    write_category("Utility Parameters", "cut")
    write_category("Labour Parameters", "col")
    write_category("Fixed Cost Parameters", "fci")
  } else {
    #Fallback: write all input parameters without categorization
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    out_params <- inpars[, c(desc_col, value_col, units_col)]
    colnames(out_params) <- c("Description", "Value", "Unit")
    fwrite(out_params, file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
  }

  #Additional results (FMC, COL)
  cat("\n\nADDITIONAL RESULTS\n", file = fpath, sep = "", append = TRUE)
  cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
  cat(names(comres[["extra"]]), file = fpath, sep = fwsep, append = TRUE)
  cat("\n", file = fpath, append = TRUE)
  cat(comres[["extra"]], file = fpath, sep = fwsep, append = TRUE)
  cat("\n", file = fpath, append = TRUE)

  #Function call
  if(is.character(funcall)) {
    cat("\n\nFUNCTION CALL\n", file = fpath, append = TRUE)
    cat(paste0(rep("-", 40), collapse = ""), "\n", file = fpath, sep = "", append = TRUE)
    cat(funcall, file = fpath, sep = "", append = TRUE)
  }
  
  if(!silent) cat("\nDONE!")
}
