#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#FUNCTION: Export desirability optimization results
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @title Export desirability optimization results
#'
#' @description Exports the results of desirability function analysis generated by \code{\link{doe_desir}} into a summary .CSV file.
#'
#' @param input The output of function \code{\link{doe_desir}}.
#' @param expath The \strong{existing} export folder path.
#' @param detailed Should detailed results be exported (\code{FALSE} by default).
#' @param silent Should updates about function progress be suppressed in the console? (\code{FALSE} by default).
#'
#' @return A .CSV file exported into \code{expath} containing desirability function analysis results.
#' @export
#'
#' @seealso \code{\link{doe_desir}}
#'
#' @importFrom data.table fwrite
#'
desir_export <- function(input, expath = getwd(), detailed = FALSE, silent = FALSE) {

  #Set the delimiter
  fwsep <- "\t"

  #Preliminary checks
  if(!dir.exists(expath)) stop("The output directory does not exist!")
  if(!all(c("factor_lims", "response_lims", "mod_sums", "orig_data", "output_data", "unique_solutions", "call" ) %in% names(input)))
    stop("The 'input' data for exporting must be output from function 'doe_desir'!")
  if(inherits(input[["call"]],"call")) input[["call"]] <- format(input[["call"]])

  #Prepare/create export directory
  fpath <- paste0(expath, "/Desirability_Function_Results_", format(Sys.time(), "%Y-%m-%d %Hhr %Mmin %Ssec"), ".tab")
  if(!silent) cat("\nExporting results to: ", fpath, "...", sep = "")

  #Export data
  exp_titles <- c("factor limits and parameters", "response limits and parameters", "model performance metrics and equations",
                  "original input data with desirability function results added",
                  "comprehensive desirabililty optimization data from random and doe starting points",
                  "unique desirability optimization solutions", "function call")
  exp_nms <- names(input)

  cat("DESIRABILITY FUNCTION RESULTS FROM ", nrow(input[["response_lims"]]),
      " MODELS EMPLOYING ", nrow(input[["factor_lims"]]), " FACTORS EACH", file = fpath, sep = "", append = TRUE)

  for(i in seq_along(exp_nms)) {
    if(!detailed & exp_nms[i]=="output_data") next else {
      cat("\n", toupper(exp_titles[i]), "\n", file = fpath, sep = "", append = TRUE)
      if(exp_nms[i]=="call") cat(input[[exp_nms[i]]], file = fpath, sep = "", append = TRUE)
      else fwrite(input[[exp_nms[i]]], file = fpath, na = "", sep = fwsep, col.names = TRUE, append = TRUE)
      cat("\n", file = fpath, append = TRUE)
    }
  }
  if(!silent) cat("\nDONE!")
}
